---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/mysql.yml
    - "vars/{{ ansible_os_family }}.yml"

  roles:
    - user
    # - sudo
    - hosts
    - ntp
    - epel
    - nux
    - dev_tools
    - xfce
    - rivendell
    - mysql
  # - touchscreen
  # - italc

  tasks:

    - name: Set timezone
      timezone:
        name: "{{ time_zone }}"
      tags: [ 'timezone']

    - name: Add "{{ locale }}" to locale.conf
      lineinfile:
        dest=/etc/locale.conf
        line="LANG={{ locale }}"
        state=present
      tags: [ "locale" ]

    - name: Stop and disable firewalld.
      service:
        name: firewalld
        state: stopped
        enabled: false
      tags: [ "firewall" ]
