---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
    - "vars/{{ ansible_os_family }}.yml"
  vars_prompt:
    - name: "user_password"
      prompt: "Enter user password"
      default: changeme
      private: yes

  roles:
    - user
    - sudo
    - epel
    - nux
    - dev_tools
    - xfce
    - rivendell
  # - touchscreen
  # - italc

  tasks:

