---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
    - "vars/{{ ansible_os_family }}.yml"
  vars_prompt:
    - name: "user_password"
      prompt: "Enter user password"
      default: changeme
      private: yes

  roles:
    - epel
    - user
  # - sudo
  # - known_hosts
    - pkgs
  # - xfce4
  # - rivendell
  # - touchscreen
  # - italc

  tasks:

    - name: Install desktop
      yum: name={{item}} state=present
      with_items: "{{ desktop }}"

    #- name: startx
      #template: src=xinitrc dest=~/.xinitrc
