---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
    - "vars/{{ ansible_os_family }}.yml"
  vars_prompt:
    - name: "user_password"
      prompt: "Enter user password"
      default: changeme
      private: yes

  roles:
    - epel
    - user
  # - sudo
  # - known_hosts
    - pkgs
  # - xfce4
  # - rivendell
  # - touchscreen
  # - italc

  tasks:

    - name: Install desktop
      yum:
        name={{item}}
        state=present
      with_items: "{{ desktop.pkgs }}"

    - name: Enable GUI on startup
      file:
        src=/usr/lib/systemd/system/graphical.target
        dest=/etc/systemd/system/default.target
        owner=root
        group=root
        state=link

    - name: Generate ~/.xinitrc file
      template:
        src=xinitrc.j2
        dest="/home/{{ user.name }}/.xinitrc"
        owner="{{ user.name }}"
        group="{{ user.group }}"
        mode=0644

    - name: Enable desktop manager service
      service:
        name="{{ item }}"
        enabled=yes
      with_items:
        - "{{ desktop.dm }}"
