---
- name: Create user group
  group:
    name={{ user.group }}
    state=present
  tags: [ "user" ]

- name: Create groups
  group:
    name="{{ item }}"
    state=present
  tags: [ "user" ]
  with_items: "{{ user.groups }}"

- name: Create user and assign to group
  user:
    name={{ user.name }}
    group={{ user.group }}
    groups="{{ item }}"
    append=yes
    password={{ user.password | password_hash('sha512') }}
    shell={{ user.shell }}
    update_password={{ user.update_password | default('always') }}
    uid={{ user.uid }}
  with_items: "{{ user.groups }}"
  tags: [ "user" ]
