---
- name: Set hostname
  hostname: name={{ inventory_hostname }}
  register: hostname
  tags: [ "hosts" ]

- name: echo /etc/hostname
  shell: echo "{{ inventory_hostname }}" > /etc/hostname
  when: hostname.changed
  tags: [ "hosts" ]

- name: Update /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item }}$'
    line="{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state=present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
  tags: [ "hosts" ]
